<?php

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once dirname(__DIR__, 2) . '/config/db.php';
require_once dirname(__DIR__, 2) . '/functions/application_functions.php';
require_once dirname(__DIR__, 2) . '/libs/composer/vendor/autoload.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    response(['status' => 'error', 'message' => 'Method not allowed.']);
}

if (empty($_POST['csrf_token']) ||
    $_POST['csrf_token'] !== ($_SESSION['csrf_token'] ?? '')) {
    http_response_code(403);
    response(['status' => 'error', 'message' => 'Invalid request.']);
}

if (!isset($_SESSION['user_uuid']) || ($_SESSION['user_role'] ?? '') !== 'student') {
    http_response_code(403);
    response(['status' => 'error', 'message' => 'Unauthorized.']);
}

if (!$conn || $conn->connect_error) {
    response([
        'status'       => 'critical',
        'message'      => 'Database connection failed.',
        'details'      => $conn->connect_error ?? 'Unknown error',
        'suggestion'   => 'Please try again later or contact support if the issue persists.'
    ]);
}

$studentUuid = $_SESSION['profile_uuid'] ?? '';
$batchUuid = $_SESSION['active_batch_uuid'] ?? '';

if ($studentUuid === '' || $batchUuid === '') {
    response(['status' => 'error', 'message' => 'Student profile or active batch is missing.'], 422);
}

$application = getStudentApplication($conn, $studentUuid, $batchUuid);
if (!$application || !in_array($application['status'], ['endorsed', 'active'], true)) {
    response(['status' => 'error', 'message' => 'No endorsed application found.'], 422);
}

$stmt = $conn->prepare("\n    SELECT p.first_name, p.last_name, p.student_id\n    FROM student_profiles p\n    WHERE p.uuid = ?\n    LIMIT 1\n");
$stmt->bind_param('s', $studentUuid);
$stmt->execute();
$student = $stmt->get_result()->fetch_assoc();
$stmt->close();

$studentName = trim(($student['first_name'] ?? '') . ' ' . ($student['last_name'] ?? ''));
$studentId = $student['student_id'] ?? 'N/A';

$issuedAt = date('F j, Y');
$statusLabel = getApplicationStatusLabel($application['status']);
$companyName = $application['company_name'] ?? 'N/A';
$dept = $application['preferred_dept'] ?? 'N/A';

$html = "
<style>
body { font-family: sans-serif; color: #1f2937; }
.title { text-align: center; font-size: 20px; font-weight: bold; margin-bottom: 6px; }
.subtitle { text-align: center; font-size: 12px; color: #6b7280; margin-bottom: 24px; }
.section { margin-bottom: 14px; line-height: 1.6; }
.label { font-weight: bold; width: 170px; display: inline-block; }
.footer { margin-top: 36px; font-size: 12px; color: #4b5563; }
</style>
<div class='title'>OJT Endorsement Confirmation</div>
<div class='subtitle'>Generated by OJT System</div>
<div class='section'><span class='label'>Student Name:</span> " . htmlspecialchars($studentName) . "</div>
<div class='section'><span class='label'>Student ID:</span> " . htmlspecialchars((string) $studentId) . "</div>
<div class='section'><span class='label'>Company:</span> " . htmlspecialchars($companyName) . "</div>
<div class='section'><span class='label'>Preferred Department:</span> " . htmlspecialchars($dept) . "</div>
<div class='section'><span class='label'>Application Status:</span> " . htmlspecialchars($statusLabel) . "</div>
<div class='section'><span class='label'>Issued On:</span> " . htmlspecialchars($issuedAt) . "</div>
<div class='footer'>
    This document confirms that the above student has an endorsed OJT application in the system.
</div>
";

$filename = 'endorsement_' . preg_replace('/[^a-z0-9_\-]/i', '_', strtolower($studentName ?: 'student')) . '.pdf';

try {
    $mpdf = new \Mpdf\Mpdf([
        'format' => 'A4',
        'margin_top' => 15,
        'margin_bottom' => 15,
    ]);
    $mpdf->WriteHTML($html);
    $mpdf->Output($filename, \Mpdf\Output\Destination::DOWNLOAD);
    exit;
} catch (Throwable $e) {
    response(['status' => 'error', 'message' => 'Unable to generate endorsement file at the moment.'], 500);
}
