<?php
session_start();

if (!isset($_SESSION['user_uuid']) || $_SESSION['user_role'] !== 'admin') {
    http_response_code(403);
    exit('Unauthorized access');
}

require_once '../../config/db.php';

$include_structure = isset($_GET['structure']) ? (int)$_GET['structure'] : 1;
$include_data = isset($_GET['data']) ? (int)$_GET['data'] : 1;
$include_drop = isset($_GET['drop']) ? (int)$_GET['drop'] : 1;

$logFile = '../../config/export_history.json';
$history = [];
if (file_exists($logFile)) {
    $history = json_decode(file_get_contents($logFile), true) ?: [];
}

$history[] = [
    'date' => date('Y-m-d'),
    'time' => date('H:i'),
    'status' => 'Success',
    'type' => 'SQL Backup'
];

if (count($history) > 10) {
    $history = array_slice($history, -10);
}

@file_put_contents($logFile, json_encode($history, JSON_PRETTY_PRINT));

set_time_limit(300);
ini_set('memory_limit', '256M');

try {
    $tables = array();
    $result = $conn->query("SHOW TABLES");
    while($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }

    $sql_content  = "-- OJT Management System - Database Export\n";
    $sql_content .= "-- OJT System Backup - Generated by OJT Management System\n";
    $sql_content .= "-- Version: 1.1.0\n";
    $sql_content .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
    $sql_content .= "-- Database: " . $dbname . "\n";
    $sql_content .= "-- Host: " . $conn->host_info . "\n\n";
    $sql_content .= "SET FOREIGN_KEY_CHECKS=0;\n";
    $sql_content .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    $sql_content .= "SET time_zone = \"+00:00\";\n\n";

    foreach($tables as $table) {
        if ($include_structure) {
            $sql_content .= "--\n-- Table structure for table `$table` \n--\n\n";
            if ($include_drop) {
                $sql_content .= "DROP TABLE IF EXISTS `$table`;\n";
            }
            
            $res = $conn->query("SHOW CREATE TABLE `$table` ");
            $row = $res->fetch_row();
            $sql_content .= $row[1] . ";\n\n";
        }
        
        if ($include_data) {
            $sql_content .= "--\n-- Dumping data for table `$table` \n--\n\n";
            $res = $conn->query("SELECT * FROM `$table` ");
            $num_fields = $res->field_count;
            
            while($row = $res->fetch_row()) {
                $sql_content .= "INSERT INTO `$table` VALUES(";
                for($j=0; $j<$num_fields; $j++) {
                    if ($row[$j] === null) {
                        $sql_content .= 'NULL';
                    } else {
                        $row[$j] = $conn->real_escape_string($row[$j]);
                        $row[$j] = str_replace("\n", "\\n", $row[$j]);
                        $row[$j] = str_replace("\r", "\\r", $row[$j]);
                        $sql_content .= '"' . $row[$j] . '"';
                    }
                    
                    if ($j < ($num_fields - 1)) {
                        $sql_content .= ',';
                    }
                }
                $sql_content .= ");\n";
            }
            $sql_content .= "\n\n";
        }
    }

    $sql_content .= "SET FOREIGN_KEY_CHECKS=1;\n";

    $filename = "ojt_backup_" . date('Y-m-d_His') . ".sql";
    
    header('Content-Type: application/sql');
    header("Content-Transfer-Encoding: Binary");
    header("Content-disposition: attachment; filename=\"" . $filename . "\"");
    
    echo $sql_content;
    exit;

} catch (Exception $e) {
    http_response_code(500);
    echo "Error during database export: " . $e->getMessage();
}
?>
